---
# tasks file for helix
- name: Install packages
  ansible.builtin.package:
    name:
      - helix
    state: present

- name: config folder exists
  file:
    path: "$HOME/.config/helix"
    state: directory
    owner: "{{ user_name }}"
    mode: 0700
  
- name: helixconfig
  ansible.builtin.template:
    src: templates/config.toml
    dest: "$HOME/.config/helix/config.toml"
    owner: "{{ user_name }}"
    mode: u+rw,g-w,o-r