---
# tasks file for helix
- name: Install packages
  become: yes
  ansible.builtin.package:
    name:
      - helix
    state: present
    update_cache: yes
  
- name: helixconfig
  ansible.buildin.template:
    src: templates/config.toml
    dest: "/home/{{ user_name }}/.config/helix/config.toml"
    owner: "{{ user_name }}"
    mode: u+rw,g-w,o-r