---
# tasks file for helix
- name: Install packages
  ansible.builtin.package:
    name:
      - helix
    state: present
  
- name: helixconfig
  ansible.builtin.template:
    src: templates/config.toml
    dest: "$HOME/.config/helix/config.toml"
    owner: "{{ user_name }}"
    mode: u+rw,g-w,o-r