---
# tasks file for helix
- name: Enable repo
  when:
    - not ansible_facts['os_family'] == "Darwin"
    - ansible_facts['distribution'] == "Fedora"
  become: true
  command:
    cmd: dnf copr enable -y varlad/helix
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:varlad:helix.repo

- name: Install packages
  when:
    - not ansible_facts['os_family'] == "Darwin"
    - ansible_facts['distribution'] == "Fedora"
  become: true
  ansible.builtin.package:
    name:
      - helix
      - rust-analyzer
    state: present

- name: Install packages
  when:
    - not ansible_facts['os_family'] == "Darwin"
    - ansible_facts['distribution'] == "Archlinux"
  become: true
  ansible.builtin.package:
    name:
      - helix
      - rust-analyzer
    state: present

- name: install mac
  when: ansible_facts['os_family'] == "Darwin"
  community.general.homebrew_tap:
    name: homebrew/helix,homebrew/rust-analyzer
    state: present

- name: config folder exists
  file:
    path: "$HOME/.config/helix"
    state: directory
    owner: "{{ user_name }}"
    mode: 0700
  
- name: helixconfig
  ansible.builtin.template:
    src: templates/config.toml
    dest: "$HOME/.config/helix/config.toml"
    owner: "{{ user_name }}"
    mode: u+rw,g-w,o-r