---
# tasks file for helix
- name: Install packages
  when: not ansible_facts['os_family'] == "Darwin"
  become: true
  ansible.builtin.package:
    name:
      - helix
      - rust-analyzer
    state: present

- name: install mac
  when: ansible_facts['os_family'] == "Darwin"
  community.general.homebrew_tap:
    name: homebrew/helix,homebrew/rust-analyzer
    state: present

- name: config folder exists
  file:
    path: "$HOME/.config/helix"
    state: directory
    owner: "{{ user_name }}"
    mode: 0700
  
- name: helixconfig
  ansible.builtin.template:
    src: templates/config.toml
    dest: "$HOME/.config/helix/config.toml"
    owner: "{{ user_name }}"
    mode: u+rw,g-w,o-r