---
# tasks file for bluetooth
- name: install bluetooth
  become: true
  ansible.builtin.package:
    name:
      - bluez
      - bluez-libs
      - bluez-utils
    state: present

- name: install bluetooth autoconnect
  ansible.builtin.command: paru -S --noconfirm --needed bluetooth-autoconnect

- name: Set controller mode
  become: true
  ansible.builtin.lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: '^ControllerMode'
    line: 'ControllerMode = bredr'
    state: present

- name: Enable bluetooth
  become: true
  ansible.builtin.service:
    name: bluetooth
    enabled: yes

- name: Enable bluetooth autoconnect
  become: true
  ansible.builtin.service:
    name: bluetooth-autoconnect
    enabled: yes
