---
# tasks file for zsh
- name: Install zsh
  when: ansible_facts['os_family'] == "Darwin"
  ansible.builtin.package:
    name:
      - zsh
      - neofetch
      - exa
      - bat
      - starship
    state: present

- name: Install zsh
  when: not ansible_facts['os_family'] == "Darwin"
  become: true
  ansible.builtin.package:
    name:
      - zsh
      - neofetch
      - exa
      - bat
      - starship
    state: present

- name: zsh folder exists
  file:
    path: "$HOME/.zsh/plugins"
    state: directory
    owner: "{{ user_name }}"
    mode: '0755'

- name: load oh-my-zsh plugins
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "$HOME/.zsh/plugins/ohmyzsh"

- name: load zsh-config plugins
  ansible.builtin.git:
    repo: https://github.com/nviennot/zsh-config.git
    dest: "$HOME/.zsh/plugins/zsh-config"

- name: load zsh-autosuggesions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "$HOME/.zsh/plugins/zsh-autosuggestions"

- name: load zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "$HOME/.zsh/plugins/zsh-syntax-highlighting"

- name: local_settings exist
  file:
    path: "$HOME/.config/local_settings"
    state: touch
    owner: "{{ user_name }}"
    mode: u+rw,g-w,o-r

- name: alias file
  ansible.builtin.template:
    src: templates/alias
    dest: "$HOME/.config/alias"
    owner: "{{ user_name }}"
    mode: u+rw,g-w,o-r

- name: zsh config
  ansible.builtin.template:
    src: templates/zshrc
    dest: "$HOME/.zshrc"
    owner: "{{ user_name }}"
    mode: u+rw,g-w,o-r