---
# tasks file for simple_git
- name: Install packages
  when: not ansible_facts['os_family'] == "Darwin"
  become: true
  ansible.builtin.package:
    name:
      - git
    state: present

- name: install git for mac
  when: ansible_facts['os_family'] == "Darwin"
  community.general.homebrew_tap:
    name: homebrew/git
    state: present

- name: Add podman user
  become: true
  user:
    name: git
    groups:
      - data
    shell: /usr/bin/git-shell
    createhome: true
    append: true

- name: Setup SSH authorized keys file
  become: yes
  authorized_key:
    user: git
    key: "{{ lookup('file', 'public_keys/fenris.pub') }}"
