version: "3"

services:
  matrix-conduit:
    container_name: matrix-conduit
    image: matrixconduit/matrix-conduit:latest
    hostname: "{{ inventory_hostname }}"
    userns_mode: keep-id
    group_add: 
      - keep-groups
      - nobody
    ports:
      - "6167:6167"
    environment:
      TZ: 'Europe/Berlin'
      CONDUIT_SERVER_NAME: "{{ server_url }}" # EDIT THIS
      CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
      CONDUIT_DATABASE_BACKEND: rocksdb
      CONDUIT_PORT: 6167
      CONDUIT_MAX_REQUEST_SIZE: 20_000_000 # in bytes, ~20 MB
      CONDUIT_ALLOW_REGISTRATION: 'false'
      CONDUIT_ALLOW_FEDERATION: 'true'
      CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
      #CONDUIT_MAX_CONCURRENT_REQUESTS: 100
      #CONDUIT_LOG: warn,rocket=off,_=off,sled=off
      CONDUIT_ADDRESS: 0.0.0.0
      CONDUIT_CONFIG: '' # Ignore this
    volumes:
      - '{{ matrix_data_path }}/config:/var/lib/matrix-conduit'
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped