---
# tasks file for fedora_rust_base

- name: install requirements
  when:
    - not ansible_facts['os_family'] == "Darwin"
    - ansible_facts['distribution'] == "Fedora"
  become: true
  ansible.builtin.package:
    name:
      - make
      - cmake
      - automake
      - gcc
      - gcc-c++
      - kernel-devel
    state: present

- name: install starship
  when:
    - not ansible_facts['os_family'] == "Darwin"
    - ansible_facts['distribution'] == "Fedora"
  ansible.builtin.command: cargo install starship

- name: install bat
  when:
    - not ansible_facts['os_family'] == "Darwin"
    - ansible_facts['distribution'] == "Fedora"
  ansible.builtin.command: cargo install bat

- name: install dust
  when:
    - not ansible_facts['os_family'] == "Darwin"
    - ansible_facts['distribution'] == "Fedora"
  ansible.builtin.command: cargo install du-dust