version: "3"

services:
  gitea:
    container_name: gitea
    image: gitea/gitea:1.19.0-rootless
    userns_mode: keep-id
    group_add: 
      - keep-groups
      - nobody
    ports:
      - "3000:3000"
      - "2222:2222"
    environment:
      TZ: 'Europe/Berlin'
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: '{{ postgres_ip }}:5432'
      GITEA__database__NAME: gitea
      GITEA__database__USER: '{{ postgres_user }}'
      GITEA__database__PASSWD: '{{ postgres_password }}'
    volumes:
      - '{{ gitea_data_path }}/data:/var/lib/gitea'
      - '{{ gitea_data_path }}/config:/etc/gitea'
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped