version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - '{{jellyfin_path}}/config:/config'
      - '{{jellyfin_path}}/cache:/cache'
      - type: bind
        source: '{{video_path}}'
        target: /media
        read_only: true
        relabel: 'private'
    ports:
      - '8096:8096/tcp'
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      JELLYFIN_PublishedServerUrl: http://jellyfin.fenris.local
      PUID: 1000
      GUID: 1000
      UMASK_SET: 022
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
