version: '3'

services:
    traefik:
        image: "traefik"
        container_name: "traefik"
        restart: "unless-stopped"
        ports:
            - "116.203.80.166:80:80"
            - "116.203.80.166:443:443"
            - "[2a01:4f8:c2c:4fec::1]:80:80"
            - "[2a01:4f8:c2c:4fec::1]:443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /traefik/letsencrypt:/letsencrypt
            - /traefik/traefik.log:/var/log/traefik.log
            - /traefik/access.log:/var/log/traefik-access.log
            - /traefik/traefik.yml:/traefik.yml:ro
            - /traefik/config.yml:/config.yml:ro
        command:
            - --accesslog=true
        labels:
            - traefik.enable=true
            - traefik.http.routers.mydashboard.rule=Host(`traefik.fenris.xyz`)
            - traefik.http.routers.mydashboard.tls=true
            - traefik.http.routers.mydashboard.tls.certresolver=myresolver
            - traefik.http.routers.mydashboard.service=api@internal
            # - traefik.http.routers.mydashboard.middlewares=myauth@file
            - traefik.http.routers.mydashboard.middlewares=myauth
            - traefik.http.middlewares.myauth.basicauth.users=fenfen:$$2y$$05$$wzQuCt2h.bxr7r7IoA/Dd.6jus8OTjnEnv73YEX1cY1tpSID5jWTO
        networks:
            - proxy

networks:
    proxy:
        enable_ipv6: true
        name: proxy
        ipam:
            driver: default
            config:
                - subnet: fd00:1::/80
                  gateway: fd00:1::1
