---
# tasks file for starcitizen
- name: Install onnxruntime for NeuralNet support
  when:
    - not ansible_facts['os_family'] == "Darwin"
    - ansible_facts['distribution'] == "Archlinux"
  ansible.builtin.command: paru -S --noconfirm --needed onnxruntime-bin

# - name: clone opentrack
#   git:
#     repo: https://git.sr.ht/~fenris/opentrack
#     dest: "{{ srcdir }}/opentrack"
#     update: true

# - name: build opentrack cmake
#   command:
#     chdir: "{{ srcdir }}/opentrack"
#     cmd: "cmake -B build -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo"
    
# - name: build opentrack cmake
#   command:
#     chdir: "{{ srcdir }}/opentrack/build"
#     cmd: "make"

  
- name: Install opentrack (git because of NeuralNet only being build into when onnxruntime is available)
  when:
    - not ansible_facts['os_family'] == "Darwin"
    - ansible_facts['distribution'] == "Archlinux"
  ansible.builtin.command: paru -S --noconfirm --needed opentrack-git
  
- name: Custom Desktop file
  when:
    - not ansible_facts['os_family'] == "Darwin"
    - ansible_facts['distribution'] == "Archlinux"
  ansible.builtin.template:
    src: templates/opentrack.desktop
    dest: "$HOME/.local/share/applications/opentrack.desktop"
    owner: "{{ user_name }}"
    mode: u+rw,g-w,o-r
