---
# tasks file for sway
- name: Install packages
  when: not ansible_facts['os_family'] == "Darwin"
  become: true
  ansible.builtin.package:
    name:
      - sway
      - python-i3ipc
      - swaylock
      - swayidle
    state: present

- name: Install AUR packages
  ansible.builtin.command: paru -S --noconfirm --needed autotiling-rs-git swaync

- name: copy sway start script
  ansible.builtin.template:
    src: templates/startsway.sh
    dest: "$HOME/bin/startsway.sh"
    owner: "{{ user_name }}"
    mode: u+rwx,g-w