---
# tasks file for wireguard
- name: Install wireguard
  when: ansible_facts['os_family'] == "Darwin"
  ansible.builtin.package:
    name:
      - wireguard-tools
    state: present

- name: Install wireguard
  when: not ansible_facts['os_family'] == "Darwin"
  become: true
  ansible.builtin.package:
    name:
      - wireguard-tools
    state: present

- name: wg config
  become: true
  ansible.builtin.template:
    src: templates/wg0.conf
    dest: "/etc/wireguard/wg0.conf"
    owner: "root"
    mode: u+rw,g-w,o-r